"""Train a leakage-conscious hybrid model from out-of-fold base predictions.

Training inputs must be generated by molecule-grouped or scaffold-grouped
validation. Final test labels must never be supplied to this script.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_PATH = PROJECT_ROOT / "src"
if str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

from chemfluor.hybrid.ensemble import save_hybrid_ensemble, train_hybrid_ensemble  # noqa: E402
from chemfluor.hybrid.meta_features import build_meta_feature_table  # noqa: E402
from chemfluor.hybrid.uncertainty import calibration_residuals  # noqa: E402

GROUP_COLUMNS = ("sample_id", "molecule_id", "candidate_id", "prediction_id")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train a hybrid ensemble from leakage-safe out-of-fold predictions."
    )
    parser.add_argument("--prediction-csv", required=True, nargs="+", type=Path)
    parser.add_argument("--target-column", required=True)
    parser.add_argument("--target-name", required=True, choices=["emission_nm", "quantum_yield"])
    parser.add_argument("--out-dir", type=Path, default=Path("models/hybrid_ensemble"))
    parser.add_argument("--coverage", type=float, default=0.90)
    parser.add_argument("--random-state", type=int, default=42)
    return parser.parse_args()


def load_examples(paths: list[Path], target_column: str) -> tuple[list[pd.DataFrame], pd.Series]:
    """Load examples, grouping a multi-example CSV when it has a stable ID."""
    tables: list[pd.DataFrame] = []
    labels: list[float] = []
    for path in paths:
        table = pd.read_csv(path)
        if target_column not in table:
            raise ValueError(f"{path} does not contain target column {target_column!r}")
        group_column = next((column for column in GROUP_COLUMNS if column in table), None)
        groups = [table] if group_column is None else [group for _, group in table.groupby(group_column, sort=False)]
        for group in groups:
            targets = pd.to_numeric(group[target_column], errors="coerce").dropna().unique()
            if len(targets) != 1:
                raise ValueError(
                    f"Each prediction example must have exactly one finite {target_column} label"
                )
            tables.append(group)
            labels.append(float(targets[0]))
    return tables, pd.Series(labels, dtype=float)


def main() -> int:
    args = parse_args()
    tables, labels = load_examples(args.prediction_csv, args.target_column)
    features = build_meta_feature_table(tables)
    if len(features) < 5:
        raise ValueError("At least five out-of-fold examples are required for split calibration")

    indices = np.arange(len(features))
    train_indices, calibration_indices = train_test_split(
        indices, test_size=max(2, int(np.ceil(0.2 * len(indices)))), random_state=args.random_state
    )
    model = train_hybrid_ensemble(
        features.iloc[train_indices], labels.iloc[train_indices], args.target_name
    )
    calibration_predictions = model["regressor"].predict(features.iloc[calibration_indices])
    confidence = (
        features.iloc[calibration_indices]["overall_confidence_score"]
        if "overall_confidence_score" in features
        else None
    )
    residuals = calibration_residuals(
        labels.iloc[calibration_indices], calibration_predictions, confidence
    )
    args.out_dir.mkdir(parents=True, exist_ok=True)
    residuals.to_csv(args.out_dir / "calibration_residuals.csv", index=False)
    save_hybrid_ensemble(
        model,
        list(features.columns),
        args.out_dir,
        {
            "target_column": args.target_column,
            "n_training_examples": int(len(train_indices)),
            "n_calibration_examples": int(len(calibration_indices)),
            "conformal_coverage": args.coverage,
            "source_files": [str(path) for path in args.prediction_csv],
        },
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
